services:
  # שירות האתר
  - type: web
    name: edulinguo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn edulinguo.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: edulinguo_db
          property: connectionString

  # עבודה מתוזמנת לאתגרים יומיים
  - type: cron
    name: daily-challenges
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "0 0 * * *"
    startCommand: python manage.py create_daily_challenges
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: edulinguo_db
          property: connectionString

databases:
  - name: edulinguo_db
    plan: starter 