# Generated by Django 4.2.7 on 2025-03-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'מתחילים'), ('intermediate', 'בינוני'), ('advanced', 'מתקדם')], default='beginner', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='משך זמן משוער בדקות', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'טקסט'), ('video', 'וידאו'), ('quiz', 'שאלון'), ('exercise', 'תרגיל'), ('flashcard', 'כרטיסיות')], max_length=20)),
                ('content', models.TextField(help_text='תוכן או קישור לתוכן')),
                ('explanation', models.TextField(blank=True, help_text='הסבר נוסף או רמזים', null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveIntegerField(default=10, help_text='נקודות שהמשתמש מקבל על השלמת האטום')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0, help_text='ציון שהמשתמש קיבל (אם רלוונטי)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningatom')),
            ],
        ),
    ]
